### ISSUE TITLE
Won't load on startup

### ISSUE THREAD

**Issue by tomspeak** [aktersnurra/no-clown-fiesta.nvim#35]
Hey, lovely theme! I am trying to get it set up and have hit a dead end in debugging.

I am using lazy.nvim as the package manager, and have reviewed a few dotfiles from people that have made issues on this repo in the past, and even when I copy their config 1:1 I cannot get it to work.

When nvim loads, the colorscheme is `default`, if I then run `:colorscheme no-clown-fiesta` it correctly sets the theme.

In `:Lazy` I can see that the colorscheme is loaded and ready.

This is my commit attempt: https://github.com/tomspeak/dotfiles/commit/05be4dafe2dd3110540df236c6bb544b414adab5

Any chance you have any ideas what is wrong here? Cheers

**Comment by aktersnurra** [comment]
I would assume that this would work:
```lua
plugin = require('no-clown-fiesta')
plugin.setup()
plugin.load()
```
I have separated the setup and load step of the colorscheme. This is obviously a bit dumb, I will fix this tonight so it will be sufficient to just call the setup function.

**Comment by aktersnurra** [comment]
If I were you, I would first remove (comment out) the other colorschemes you have in the plugin table, idk if the init function is executed even if the `enabled = false`, so just as a precaution. Then I would also remove:

```lua
    priority = 1000,
```

I don't have this parameter set, so try without it.

I would also remove this [line](https://github.com/tomspeak/dotfiles/blob/88f6b44b972e8232f987e664a20ce355d0094acb/kickstart/init.lua#L262C25-L262C26) if you call `p.load()`. Since the do the same thing.
