### ISSUE TITLE
Undercurl support

### ISSUE THREAD

**Issue by caliguIa** [aktersnurra/no-clown-fiesta.nvim#44]
It would be nice to have under curl support for errors. I'm unsure how this is implemented but I know that tokyonight and catppuccin support it. If I can provide any other info please let me know!

<img width="465" alt="Screenshot 2024-10-24 at 12 11 41" src="https://github.com/user-attachments/assets/eb16b4a2-e31e-463d-a876-e229825e28b1">

**Comment by aktersnurra** [comment]
I could not find anything special done in tokyonight. But I will investigate this a bit because this is for sure annoying.

I assume that it has nothing to do with your terminal and/or tmux configuration?

But I highly suspect the problem is somewhere on my side since it worked before and does not work now (even for me (when I tried it now)).

**Comment by caliguIa** [comment]
Thanks, I'm happy to do a bit of exploring this evening also and will let you know if I find anything. Nah my setup is fine, if I switch my colour scheme back to Catppuccin under curl works. Thanks!

**Comment by aktersnurra** [comment]
Try now, maybe the default settings where `underline = true` was messing with you? 
You get the correct color on the underline/curl right? (I do not, but that might be because I am rolling nightly)

**Comment by caliguIa** [comment]
That's working now, thank you! I'm Loving the colour scheme a lot, my coworkers on screen share are not...  ha!

**Comment by caliguIa** [comment]
Worth noting I do need to specify the following to get it working, which is expected i think, but just as a heads up :) 

```
            styles = {
                lsp = {
                    undercurl = true,
                },
                type = { bold = true },
            },
```

**Comment by aktersnurra** [comment]
Happy to help! Yeah, it can be quite dark compared to others I guess.

**Comment by caliguIa** [comment]
Not related to this issue, but I've just setup a Wezterm scheme for the theme, I noticed that you have a no-clown-fiesta org with a separate repo for this there. Should we be using the repo from the org instead of this one?

**Comment by aktersnurra** [comment]
I am not exactly sure which repo you are referring when you say "this". If you want me to invite you to the org so that you can contribute these settings to a repo called `no-clown-fiesta.wezterm`, then I am happy to assist. However, terminal settings should not be included in the nvim repo if that is what you were asking?

Also, the github repositories are simply two of "many" mirrors, I would not consider any one of these the master repo.

**Comment by caliguIa** [comment]
Okay cool, I was just wondering about the mirror repos, and if we should use one over the other. All good will continue using the one linked to your user account. :)

I have the colour scheme setup and in a structure following examples from other big colourschemes, for wezterm. I'm very happy to contribute it to a wezterm repo if you make one! Let me know what you decide! 😄  Thanks again for this scheme, falling in love with it the more i use it!

**Comment by aktersnurra** [comment]
here is the [repository](https://github.com/no-clown-fiesta/no-clown-fiesta.wezterm) you can contribute to if you want to.
