### ISSUE TITLE
Any plans to color JSX elements?

### ISSUE THREAD

**Issue by ChrisMGeo** [aktersnurra/no-clown-fiesta.nvim#7]
As of now JSX elements are just the same as the normal foreground color. Any plans to make it a different color like the desaturated teal or sky blue you use?

**Comment by aktersnurra** [comment]
No, I don't develop in js so I don't face this problem. However, if a jsx element gets interpreted as one of the supported types, e.g. keywords, variables or type, you can always make it stand out by configuring it to be bold and/or italic. I do it for type for example for other languages. 

Otherwise I suggest that you fork this and look at the [treesitter](https://github.com/aktersnurra/no-clown-fiesta.nvim/blob/master/lua/no-clown-fiesta/highlight-group/treesitter.lua) to change the color corresponding to jsx type.

Cheers.
